name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v3

      - name: 💾 Install modules
        run: npm ci

      - name: 🧪 Testing
        run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DEBUG: ${{ secrets.DEBUG }}
          MONGODB_CONNECTION: ${{ secrets.MONGO_DB_CONNECTION }}
          ALLOEWD_ORIGIN: ${{ secrets.ALLOEWD_ORIGIN}}
